apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  labels:
    app: devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
      - name: nodejs-app
        image: ubuntu/nginx:1.18-20.04_beta
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/devsecopsdb"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
