name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Run Static Code Analysis (Semgrep)
        uses: returntocorp/semgrep-action@v1

      - name: Docker Build, Scan, and Push
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: vamanrathod24/VoiceOwL-app:latest
          labels: type=semver
          login: true
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      
