- name: Checkout repository
  uses: actions/checkout@v3

- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18

- name: Install dependencies
  run: npm install
  working-directory: ./app

- name: Semgrep Scan
  uses: returntocorp/semgrep-action@v1

- name: Docker Hub Login
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

- name: Build & Push Docker Image
  uses: docker/build-push-action@v3
  with:
    context: ./app
    push: true
    tags: vamanrathod24/voiceowl-app:latest
