name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Cache npm dependencies
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install npm dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./app

      # 5️⃣ Run static code analysis (Semgrep)
      - name: Run Static Code Analysis (Semgrep)
        uses: returntocorp/semgrep-action@v1

      # 6️⃣ Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7️⃣ Build and push Docker image with caching
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: vamanrathod199/voiceowl-app-1:latest
          labels: type=semver
          cache-from: type=registry,ref=vamanrathod199/voiceowl-app-1:cache
          cache-to: type=registry,ref=vamanrathod199/voiceowl-app-1:cache,mode=max

      # 8️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4

      # 9️⃣ Terraform Init & Plan
      - name: Terraform Init and Plan
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform init
          terraform plan -out=tfplan

      # 🔟 Terraform Apply (only on main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform apply -auto-approve tfplan

      # 1️⃣1️⃣ Decode Kubeconfig for deployment
      - name: Decode Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      # 1️⃣2️⃣ Deploy to Kubernetes
      - name: Deploy to Kubernetes
        uses: appleboy/kubernetes-action@v0.3.4
        with:
          kubeconfig: $HOME/.kube/config
          manifests: |
            ./k8s/deployment.yaml
            ./k8s/service.yaml
